export const SEARCH_SETING_REQUEST = 'SEARCH_SETING_REQUEST';
export const SEARCH_SETING_FAILURE = 'SEARCH_SETING_FAILURE';
export const SEARCH_SETING_SUCCESS = 'SEARCH_SETING_SUCCESS';
export const CHANGE_SEARCH   = 'CHANGE_SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';